const abbreviations = [
  "AGO",
  "APA",
  "BIS",
  "BEIS",
  "CO",
  "CXD",
  "DCLG",
  "DCMS",
  "DECC",
  "DEFRA",
  "DE&S",
  "DEXEU",
  "DFE",
  "DFID",
  "DFT",
  "DH",
  "DHSC",
  "DMO",
  "DPM",
  "DVLA",
  "DWP",
  "ERG",
  "FCO",
  "GAD",
  "GDS",
  "HCS",
  "HMRC",
  "HMT",
  "HO",
  "HOFC",
  "HOFL",
  "IPA",
  "LAW",
  "MHCLG",
  "MOD",
  "MOJ",
  "MPA",
  "NAO",
  "NHS",
  "NICS",
  "NIO",
  "NS&I",
  "OBR",
  "ONS",
  "PM",
  "SCOT",
  "SG",
  "WAL",
  "WG",
];
const organisations = [
  "Attorney General's Office",
  "Asset Protection Agency",
  "Department for Business, Innovation and Skills",
  "Department for Business, Energy and Industrial Strategy",
  "Cabinet Office",
  "Chancellor's Departments (APA, DMO, GAD, HMRC, HMT, NS&I, OBR)",
  "Department for Communities and Local Government",
  "Department for Digital, Culture, Media and Sport",
  "Department of Energy and Climate Change",
  "Department for Environment, Food and Rural Affairs",
  "Defence Equipment and Support (part of MoD)",
  "Department for Exiting the European Union",
  "Department for Education",
  "Department for International Development",
  "Department for Transport",
  "Department of Health",
  "Department of Health and Social Care",
  "Debt Management Office",
  "Deputy Prime Minister",
  "Driver and Vehicle Licensing Agency (part of DfT)",
  "Department for Work and Pensions",
  "Efficiency and Reform Group (part of CO)",
  "Foreign and Commonwealth Office",
  "Government Actuary's Department",
  "Government Digital Service",
  "Home Civil Service (all civil servants in UK, Scottish and Welsh governments)",
  "Her Majesty's Revenue and Customs",
  "Her Majesty's Treasury",
  "Home Office",
  "House of Commons",
  "House of Lords",
  "Infrastructure and Projects Authority",
  "Law officers (AGO, Office of the Advocate General for Scotland)",
  "MInistry of Housing, Communities and Local Government",
  "Ministry of Defence",
  "Ministry for Justice",
  "Major Projects Authority (part of CO)",
  "National Audit Office",
  "National Health Service",
  "Northern Ireland Civil Service",
  "Northern Ireland Office",
  "National Savings and Investments",
  "Office for Budget Responsibility",
  "Office for National Statistics",
  "Prime Minister",
  "Scotland Office",
  "Scottish Government",
  "Wales Office",
  "Welsh Government",
];
let obj = {};

abbreviations.forEach((element, index) => {
  obj[element] = organisations[index];
});

export default obj;
